# Generated by Django 4.2 on 2023-05-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0003_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
